$(CC) = cc -Wextra -Werror -Wall

compile:
	$(CC) main.c get_number.c get_number2.c parse.c struct_norm_not_ok.c conditions123.c write_numbers.c print_logs.c basic_functions.c bloc_trans.c -o rush-02

fclean:
	rm rush-02

